Repository AMReX-Codes/amrex, pull requests merged in 2020-07, with the labels that each got.

#1079 CMake: add support for MPI multiple threads
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReX_Config.H.in
  Tools/CMake/AMReX_Defines.cmake
  Tools/CMake/AMReX_Options.cmake
Labels: enhancement, install

#1101 CMake: forgot to print option ENABLE_MPI_THREAD_MULTIPLE
  Tools/CMake/AMReX_Options.cmake
Labels: enhancement

#1081 CMake: Fix CUDA Host Check
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: install, workaround

#1112 Tutorials: Build System Race Condition
  Tutorials/Amr/Advection_AmrLevel/CMakeLists.txt
  Tutorials/SENSEI/Advection_AmrLevel/CMakeLists.txt
Labels: bug, install, test

#1111 add AMREX_NO_INLINE attribute
  Src/Base/AMReX_Extension.H
Labels: enhancement

#1127 AppleClang, MSVC: Avoid Malformed Config.H
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: bug, install

#1126 FORTLINK: Guess if Unknown
  Tools/CMake/AMReX_Defines.cmake
Labels: install, workaround

#1138 Fix compilation of AMReX_CommProfStats.cp for non-3D builds
  Src/Extern/ProfParser/AMReX_CommProfStats.cpp
Labels: bug

#1140 work with ax3l: fail when fortran c interface could not be found
  Tools/CMake/AMReX_Defines.cmake
Labels: enhancement, install

#1134 CMake: fix missing PETSc setup in Config file
  Tools/CMake/AMReXConfig.cmake.in
Labels: install

#1103 CMake: re-factor parallel backends setup
  Src/Base/CMakeLists.txt
  Src/CMakeLists.txt
  Src/F_Interfaces/CMakeLists.txt
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: enhancement, install

#1139 Fix line length issues in fixed-form Fortran sources
  Src/CMakeLists.txt
  Src/Extern/ProfParser/AMReX_AVGDOWN_2D.F
  Src/Extern/ProfParser/AMReX_AVGDOWN_3D.F
  Src/Extern/amrdata/AMReX_FABUTIL_2D.F
  Src/Extern/amrdata/AMReX_FABUTIL_3D.F
  Tools/CMake/AMReXFlagsTargets.cmake
Labels: enhancement

#1095 CMake: More NVCC Controls
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: GPU, install

#1147 add github action for 1D and 2D using configure
  .github/workflows/linux.yml
Labels: test

#1149 CMake: implement ability to export build tree
  Src/CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReXInstallHelpers.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: enhancement

#1164 update CONTRIBUTING.md on how to fix git commits to have a clean history
  CONTRIBUTING.md
Labels: documentation

#1176 WARN_ALL
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/AmrCore/AMReX_Cluster.cpp
  Src/AmrCore/AMReX_FluxRegister.cpp
  Src/AmrCore/AMReX_Interp_3D_C.H
  Src/Base/AMReX_BCUtil.cpp
  Src/Base/AMReX_BaseFab.H
  Src/Base/AMReX_CArena.H
  Src/Base/AMReX_CoordSys.cpp
  Src/Base/AMReX_EArena.H
  Src/Base/AMReX_FArrayBox.cpp
  Src/Base/AMReX_FBI.H
  Src/Base/AMReX_FabArray.H
  Src/Base/AMReX_FabArrayBase.cpp
  Src/Base/AMReX_FabArrayCommI.H
  Src/Base/AMReX_FabArrayUtility.H
  Src/Base/AMReX_FabConv.cpp
  Src/Base/AMReX_FilCC_C.cpp
  Src/Base/AMReX_FilND_C.cpp
  Src/Base/AMReX_GpuAsyncArray.cpp
  Src/Base/AMReX_GpuDevice.cpp
  Src/Base/AMReX_GpuElixir.cpp
  Src/Base/AMReX_GpuLaunch.H
  Src/Base/AMReX_GpuLaunchFunctsC.H
  Src/Base/AMReX_MFCopyDescriptor.cpp
  Src/Base/AMReX_MultiFab.cpp
  Src/Base/AMReX_MultiFabUtil.cpp
  Src/Base/AMReX_PODVector.H
  Src/Base/AMReX_ParallelDescriptor.cpp
  Src/Base/AMReX_PlotFileUtil.cpp
  Src/Base/AMReX_Random.cpp
  Src/Base/AMReX_Reduce.H
  Src/Base/AMReX_TinyProfiler.cpp
  Src/Base/AMReX_VisMF.cpp
  Src/Boundary/AMReX_InterpBndryData.H
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.cpp
  Src/LinearSolvers/MLMG/AMReX_MLALaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLCellABecLap.H
  Src/LinearSolvers/MLMG/AMReX_MLCellLinOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLLinOp.H
  Src/LinearSolvers/MLMG/AMReX_MLLinOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLLinOp_K.H
  Src/LinearSolvers/MLMG/AMReX_MLMG.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeLap_3D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLNodeLaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLNodeLinOp.H
  Src/LinearSolvers/MLMG/AMReX_MLNodeLinOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeTensorLap_3D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLNodeTensorLaplacian.cpp
  Src/LinearSolvers/MLMG/AMReX_MLPoisson.H
  Src/LinearSolvers/MLMG/AMReX_MLPoisson.cpp
  Src/LinearSolvers/MLMG/AMReX_MLTensorOp.H
  Src/LinearSolvers/MLMG/AMReX_MLTensorOp.cpp
  Src/Particle/AMReX_ParticleCommunication.cpp
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleUtil.H
  Tools/GNUMake/Make.defs
  Tools/GNUMake/comps/gnu.mak
  Tools/GNUMake/comps/llvm.mak
Labels: install, warning

#1180 Fix c++11 float narrowing
  Src/AmrCore/AMReX_ErrorList.cpp
Labels: bug

#1182 Wreorder: ErrorList
  Src/AmrCore/AMReX_ErrorList.H
Labels: warning

#1181 CI: Clang 6.0 C++17 SP NOMPI
  .github/workflows/dependencies/dependencies_clang6.sh
  .github/workflows/linux.yml
Labels: test

#1196 Gcc7 no array bounds
  Src/Base/AMReX_Extension.H
  Src/LinearSolvers/MLMG/AMReX_MLMG.cpp
  Tools/GNUMake/comps/gnu.mak
Labels: warning

#1197 Fix some more clang warnings
  Src/AmrCore/AMReX_ErrorList.cpp
  Src/AmrCore/AMReX_FillPatchUtil.cpp
  Src/Base/AMReX_Array.H
  Src/Base/AMReX_Box.H
  Src/Base/AMReX_CoordSys.H
  Src/Base/AMReX_CoordSys.cpp
  Src/Base/AMReX_Geometry.H
  Src/Base/AMReX_Geometry.cpp
  Src/Base/AMReX_Machine.cpp
  Src/Base/AMReX_MultiFabUtil.cpp
  Src/Base/AMReX_ParallelReduce.H
  Src/Base/AMReX_PhysBCFunct.H
  Src/Base/AMReX_PlotFileDataImpl.cpp
  Src/Boundary/AMReX_YAFluxRegister.cpp
  Src/F_Interfaces/AmrCore/AMReX_FlashFluxRegister.cpp
  Src/F_Interfaces/AmrCore/AMReX_fluxregister_fi.cpp
  Src/F_Interfaces/LinearSolvers/AMReX_abeclaplacian_fi.cpp
  Src/F_Interfaces/LinearSolvers/AMReX_linop_fi.cpp
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.cpp
  Src/LinearSolvers/MLMG/AMReX_MLALaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLCellLinOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLLinOp.H
  Src/LinearSolvers/MLMG/AMReX_MLLinOp_K.H
  Src/LinearSolvers/MLMG/AMReX_MLMGBndry.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeLap_K.H
  Src/LinearSolvers/MLMG/AMReX_MLPoisson.H
  Src/Particle/AMReX_ParticleCommunication.H
  Src/Particle/AMReX_TracerParticles.cpp
Labels: warning

#1206 CMake: NVCC/cudafe Error Numbers
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: GPU, install
