Repository AMReX-Codes/amrex, pull requests merged in 2020-10, with the labels that each got.

#1428 CMake: fix ENABLE_PROFPARSER and ENABLE_SENSEI options
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/CMakeLists.txt
  Src/Extern/amrdata/CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXThirdPartyLibraries.cmake
  Tools/CMake/AMReX_Defines.cmake
  Tools/CMake/AMReX_Options.cmake
Labels: install

#1440 GNUmake: -Titan (OLCF)
  Tools/GNUMake/Make.machines
  Tools/GNUMake/sites/Make.olcf
Labels: bug, install

#1316 CMake: add HIP support
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/linux.yml
  Docs/sphinx_documentation/source/GPU.rst
  Src/CMakeLists.txt
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReXTargetHelpers.cmake
  Tools/CMake/AMReX_Defines.cmake
  Tools/CMake/AMReX_Options.cmake
  Tutorials/CMakeLists.txt
  Tutorials/Particles/CellSortedParticles/CMakeLists.txt
Labels: GPU, install, test

#1462 CI: rocRAND v1.8.2
  .github/workflows/dependencies/dependencies_hip.sh
Labels: install

#1468 CMake: improve HDF5 support
  Tests/CMakeLists.txt
  Tests/HDF5Benchmark/CMakeLists.txt
  Tools/CMake/AMReXThirdPartyLibraries.cmake
Labels: bug, install

#1469 Gpu::Atomic::AddNoRet
  Src/Base/AMReX_FBI.H
  Src/Base/AMReX_GpuAtomic.H
  Src/Base/AMReX_GpuReduce.H
  Src/Base/AMReX_MultiFab.cpp
  Src/Base/AMReX_TypeTraits.H
  Src/EB/AMReX_EB_utils.cpp
  Src/Particle/AMReX_DenseBins.H
  Src/Particle/AMReX_Particle_mod_K.H
  Tests/Particles/NeighborParticles/MDParticleContainer.cpp
  Tests/Particles/ParticleMesh/main.cpp
  Tutorials/Particles/ElectromagneticPIC/Exec/CUDA/em_pic_K.H
Labels: GPU

#1480 CMake 3.18+: CUDA Arch Policy (OLD)
  CMakeLists.txt
Labels: GPU, install, warning

#1482 Workaround for Mac CI
  .github/workflows/dependencies/dependencies_mac.sh
Labels: workaround

#1481 Fix warning in FabSet for single precision
  Src/Boundary/AMReX_FabSet.cpp
Labels: warning

#1484 CI: -Werror for host compilers
  .github/workflows/linux.yml
  .github/workflows/macos.yml
Labels: test, warning

#1467 HIP GNU Make: need to override COMP for regression tests
  Tools/GNUMake/Make.defs
Labels: GPU, test

#1486 CI: Check More Warnings
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  Src/Particle/AMReX_NeighborParticles.H
  Tutorials/Basic/PrefixSum_MultiFab/main.cpp
  Tutorials/Particles/CellSortedParticles/cell_sorted_F.H
  Tutorials/Particles/ElectromagneticPIC/Exec/OpenMP/em_pic_F.H
  Tutorials/Particles/ElectrostaticPIC/ElectrostaticParticleContainer.cpp
  Tutorials/Particles/NeighborList/MDParticleContainer.cpp
Labels: test, warning

#1488 Ascent: Use Default Name for Mesh Ghost
  Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp
Labels: bug
