Repository AMReX-Codes/amrex, pull requests merged in 2020-06, with the labels that each got.

#946 CMake: improve handling of options
  CMakeLists.txt
  Src/Extern/SUNDIALS4/CMakeLists.txt
  Tools/CMake/AMReX_Options.cmake
Labels: install

#947 Windows
  .github/workflows/windows.yml
  Src/Amr/AMReX_Amr.cpp
  Src/Amr/AMReX_AmrLevel.cpp
  Src/Amr/AMReX_AsyncFillPatch.cpp
  Src/Amr/AMReX_StateData.cpp
  Src/Base/AMReX.cpp
  Src/Base/AMReX_Arena.cpp
  Src/Base/AMReX_Array4.H
  Src/Base/AMReX_BLBackTrace.H
  Src/Base/AMReX_BLBackTrace.cpp
  Src/Base/AMReX_BaseFab.H
  Src/Base/AMReX_Extension.H
  Src/Base/AMReX_FPC.cpp
  Src/Base/AMReX_FabArray.H
  Src/Base/AMReX_FabArrayCommI.H
  Src/Base/AMReX_FileSystem.H
  Src/Base/AMReX_FileSystem.cpp
  Src/Base/AMReX_GpuAsyncArray.H
  Src/Base/AMReX_GpuControl.H
  Src/Base/AMReX_GpuLaunch.H
  Src/Base/AMReX_GpuMemory.H
  Src/Base/AMReX_GpuRange.H
  Src/Base/AMReX_MemProfiler.cpp
  Src/Base/AMReX_ParallelDescriptor.H
  Src/Base/AMReX_ParallelDescriptor.cpp
  Src/Base/AMReX_SPACE.H
  Src/Base/AMReX_Utility.H
  Src/Base/AMReX_Utility.cpp
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
  Src/EB/AMReX_EB2_3D_C.cpp
  Src/EB/AMReX_EB2_IF_Complement.H
  Src/EB/AMReX_EB2_IF_Difference.H
  Src/EB/AMReX_EB2_IF_Extrusion.H
  Src/EB/AMReX_EB2_IF_Intersection.H
  Src/EB/AMReX_EB2_IF_Lathe.H
  Src/EB/AMReX_EB2_IF_Rotation.H
  Src/EB/AMReX_EB2_IF_Scale.H
  Src/EB/AMReX_EB2_IF_Translation.H
  Src/EB/AMReX_EB2_IF_Union.H
  Src/EB/AMReX_EBMultiFabUtil.cpp
  Src/EB/AMReX_EB_utils.cpp
  Src/LinearSolvers/MLMG/AMReX_MLCellLinOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap.cpp
  Src/LinearSolvers/MLMG/AMReX_MLEBTensorOp.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeLaplacian.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeTensorLap_2D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLTensorOp.cpp
  Src/Particle/AMReX_ParticleIO.H
  Tests/AsyncOut/multifab/main.cpp
  Tests/IOBenchmark/IOTestDriver.cpp
  Tests/MKDir/MKDir.cpp
  Tools/AMRProfParser/TestCodes/AMRProfTest0.cpp
  Tools/AMRProfParser/TestCodes/ProfWaitTest.cpp
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: enhancement

#965 ParticleIO: Update Arg Signature Usage
  Src/Particle/AMReX_ParticleIO.H
Labels: bug

#966 make sure we enable particles in cmake CI
  .github/workflows/linux.yml
  .github/workflows/macos.yml
Labels: test

#964 CMake CUDA: Cleanups & CCache
  Tools/CMake/AMReX_Config.cmake
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: install, performance

#971 CI: Mainly Debug
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: test

#980 Make: use -M to generate dependencies
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.rules
  Tools/GNUMake/comps/cray.mak
  Tools/GNUMake/comps/nvcc.mak
Labels: bug, install

#1009 CMake: MSVC Pre-Processor Flags (Fix Old/New)
  Tools/CMake/AMReXFlagsTargets.cmake
Labels: install

#1012 CI: Verbose Make
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: test

#1011 Single Precision: INVALID_TIME Value OoR
  Src/Amr/AMReX_StateData.cpp
Labels: bug

#1017 CMake: set minimum C++ standard to 17 for Windows builds
  .github/workflows/windows.yml
  Tools/CMake/AMReX_Config.cmake
Labels: enhancement, install

#1016 CMake: add support for DPCPP
  CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReX_Config.cmake
  Tools/CMake/AMReX_Defines.cmake
  Tools/CMake/AMReX_Options.cmake
Labels: GPU, enhancement, install

#1031 Conduit: Fix CMake Target Typo
  Src/Extern/Conduit/CMakeLists.txt
Labels: bug, install

#1034 CMake: create SYCL target to handle dpcpp builds
  Src/CMakeLists.txt
  Tools/CMake/AMReXSYCL.cmake
  Tools/CMake/AMReX_Config.H.in
  Tools/CMake/AMReX_Config.cmake
Labels: enhancement

#1032 Conduit: Work-Around Missing Const
  Src/Extern/Conduit/AMReX_Conduit_Blueprint_ParticlesI.H
Labels: bug, workaround

#1037 CMake Summary: No Fortran
  Tools/CMake/AMReX_Config.cmake
Labels: install

#943 CI: DPC++
  .github/workflows/cmake/dependencies_dpcpp.sh
  .github/workflows/linux.yml
Labels: GPU, test

#1038 fix a tutorial for dpc++ (and cuda)
  Tutorials/LinearSolvers/MultiComponent/MCNodalLinOp.cpp
Labels: GPU, bug, test

#1052 CMake: simplify configuration option summary
  Tools/CMake/AMReX_Options.cmake
Labels: install
