Repository AMReX-Codes/amrex, pull requests merged in 2020-11, with the labels that each got.

#1493 GNUMake: Merge Ascent and Peak with Summit
  Tools/GNUMake/sites/Make.olcf
Labels: install

#1516 CMake: fix some quirks with options output
  Tools/CMake/AMReXOptions.cmake
Labels: install

#1511 CMake: add component check for Fortran
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXConfig.cmake.in
Labels: documentation, install

#1514 CMake: fix options name in Test directory
  Tests/CMakeLists.txt
  Tests/HDF5Benchmark/CMakeLists.txt
Labels: bug, install, test

#1520 make clean & make cleanconfig
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.rules
  Tools/GNUMake/README.md
  Tools/GNUMake/comps/hip.mak
  Tools/GNUMake/comps/nvcc.mak
  Tools/GNUMake/sites/Make.unknown
Labels: install

#1522 Change Spelling: Env AMREX_CUDA_ARCH
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: install

#1512 Support CUDA arch < 6.0
  Src/Base/AMReX_BaseFab.H
  Src/Base/AMReX_GpuAtomic.H
  Src/Base/AMReX_GpuDevice.H
  Src/Base/AMReX_GpuDevice.cpp
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: GPU

#1515 Ascent: Check Bounds Particle Reals
  Src/Extern/Conduit/AMReX_Conduit_Blueprint_ParticlesI.H
Labels: enhancement

#1545 CMake: generate_buildinfo target
  Tools/CMake/AMReXBuildInfo.cmake
Labels: install

#1552 CMake: improvements to handling of buildInfo
  Tools/CMake/AMReXBuildInfo.cmake
Labels: bug, install

#1550 CMake: Fix Single-Precision Switch
  Src/Particle/CMakeLists.txt
  Tools/CMake/AMReX_Config.H.in
  Tools/CMake/AMReX_Defines.cmake
Labels: bug, install

#1555 CMake: AMReX_MPI options is dependent on SYCL, not HIP
  Tools/CMake/AMReXOptions.cmake
Labels: GPU, install

#1521 Scan size type
  Src/Base/AMReX_Scan.H
Labels: enhancement

#1563 CMake: OpenMP for Fortran
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXParallelBackends.cmake
Labels: bug, install, performance

#1556 DPCPP: MPI
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.machines
  Tools/GNUMake/comps/dpcpp.mak
  Tools/GNUMake/sites/Make.alcf
Labels: GPU

#1568 CI: Make DPC++ Pretty
  .github/workflows/linux.yml
Labels: GPU, test
