Repository AMReX-Codes/amrex, pull requests merged in 2020-05, with the labels that each got.

#833 CMake: do not install Fortran modules if Fortran is not enabled
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: install

#835 CMake: make AMReX_buildInfo.cpp always out of date
  Tools/CMake/AMReXBuildInfo.cmake
  Tools/CMake/AMReX_buildInfo.cpp.in
Labels: enhancement, install

#841 User literals: add a space before _ to make gcc 4.8 happy
  Src/Base/AMReX_REAL.H
Labels: workaround

#851 CMake: link against OpenMP_Fortran only when Fortran is enabled
  Tools/CMake/AMReX_Config.cmake
Labels: install

#865 DPCPP Makefile: Fix CC Typo
  Tools/GNUMake/comps/dpcpp.mak
Labels: GPU, install

#868 GNUMake: fix mispelled header name
  Src/EB/Make.package
Labels: bug

#869 add inline namespace literals and use in CNS and Heat Equation tutorials
  Src/Base/AMReX_REAL.H
  Tutorials/Basic/HeatEquation_EX1_C/Source/main.cpp
  Tutorials/Basic/HeatEquation_EX1_C/Source/myfunc.H
  Tutorials/Basic/HeatEquation_EX1_C/Source/myfunc.cpp
  Tutorials/Basic/HeatEquation_EX1_C/Source/mykernel.H
  Tutorials/GPU/CNS/Exec/RT/cns_prob.H
  Tutorials/GPU/CNS/Exec/RT/cns_prob_parm.H
  Tutorials/GPU/CNS/Exec/Sod/cns_prob.H
  Tutorials/GPU/CNS/Exec/Sod/cns_prob_parm.H
  Tutorials/GPU/CNS/Source/CNS.cpp
  Tutorials/GPU/CNS/Source/CNS_K.H
  Tutorials/GPU/CNS/Source/CNS_advance.cpp
  Tutorials/GPU/CNS/Source/CNS_parm.H
  Tutorials/GPU/CNS/Source/CNS_parm.cpp
  Tutorials/GPU/CNS/Source/hydro/CNS_hydro_K.H
  Tutorials/GPU/CNS/Source/main.cpp
Labels: enhancement

#866 CMake: add helper function setup_target_for_cuda_compilation()
  Src/CMakeLists.txt
  Tools/CMake/AMReXTargetHelpers.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: GPU, install

#936 CMAKE_INSTALL_PREFX: Only Toplevel
  CMakeLists.txt
Labels: install

#939 Add cstdlib header to AMReX_Math.H
  Src/Base/AMReX_Math.H
Labels: bug

#927 Atomics: Constify Wrapper
  Src/Base/AMReX_GpuAtomic.H
Labels: GPU

#941 remove const for compare_exchange_strong
  Src/Base/AMReX_GpuAtomic.H
Labels: GPU

#948 GH Action CI: Restructure
  .github/workflows/dependencies/dependencies.sh
  .github/workflows/dependencies/dependencies_mac.sh
  .github/workflows/dependencies/dependencies_nofortran.sh
  .github/workflows/dependencies/dependencies_nvcc.sh
  .github/workflows/linux.yml
  .github/workflows/macos.yml
Labels: test

#949 C++20 Compatibility: GCC 10.1
  .github/workflows/dependencies/dependencies.sh
  .github/workflows/dependencies/dependencies_gcc10.sh
  .github/workflows/dependencies/dependencies_mac.sh
  .github/workflows/linux.yml
Labels: test
