Repository AMReX-Codes/amrex, pull requests merged in 2020-08, with the labels that each got.

#1131 Tools: add NVIDIA HPC SDK as a compiler
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.rules
  Tools/GNUMake/comps/hpcsdk.mak
Labels: install

#1208 CI: Fix oneAPI Activation
  Tools/CMake/AMReXSYCL.cmake
  Tools/GNUMake/comps/dpcpp.mak
Labels: GPU, bug, test, workaround

#1252 CMake: re-factor third party libraries setup
  Src/CMakeLists.txt
  Src/Extern/Conduit/CMakeLists.txt
  Src/Extern/HYPRE/CMakeLists.txt
  Src/Extern/PETSc/CMakeLists.txt
  Src/Extern/SENSEI/CMakeLists.txt
  Src/Extern/SUNDIALS4/CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXThirdPartyLibraries.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: install

#1284 Add section to Make.unknown for intel mpi
  Tools/GNUMake/sites/Make.unknown
Labels: enhancement, install
