Repository AMReX-Codes/amrex, pull requests merged in 2020-12, with the labels that each got.

#1588 CI: Windows + Clang
  .github/workflows/windows.yml
Labels: test

#1572 CMake: output missing components list when AMReX is not found
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: install

#1591 CI: Tutorial with OMP
  .github/workflows/linux.yml
  Tutorials/Particles/ElectromagneticPIC/CMakeLists.txt
Labels: test

#1593 Fix: Windows and/or includes (iso646)
  Src/Base/AMReX_Extension.H
  Src/Base/AMReX_Vector.H
  Src/Particle/AMReX_ParticleTile.H
Labels: bug

#1602 CI: Disable DPC++ oneAPI 2020-11
  .github/workflows/linux.yml
Labels: GPU, test

#1613 DPC++: Re-Enable with Work-around.
  .github/workflows/linux.yml
Labels: GPU, install, test, workaround

#1615 Conduit: Fix unused variables
  Src/Extern/Conduit/AMReX_Conduit_Blueprint.cpp
Labels: warning

#1619 CMake: Verify DPC++ Compiler ID and at best warn
  Tools/CMake/AMReXOptions.cmake
Labels: GPU, install

#1626 Warning in SP: large ICC float constant
  Src/Amr/AMReX_Amr.cpp
Labels: warning

#1647 CMake: Fix Typos in SYCL Warnings
  Tools/CMake/AMReXOptions.cmake
Labels: install

#1652 CI: fix macOS
  .github/workflows/dependencies/dependencies_mac.sh
Labels: test, workaround

#1561 CMake: fix few quirks with GPU backends variables
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXOptions.cmake
Labels: GPU, install

#1645 CMake: AMRDATA needs Fortran
  Tools/CMake/AMReXOptions.cmake
Labels: install

#1659 Fix how fextract handles the tolerance option
  Tools/Plotfile/fextract.cpp
Labels: bug

#1661 CMake: streamline install of plotfile tools
  CMakeLists.txt
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXInstallHelpers.cmake
  Tools/Plotfile/CMakeLists.txt
Labels: install

#1662 CI: Lib + Plotfiles Install
  .github/workflows/linux.yml
Labels: install, test

#1653 CI: CUDA 9.1 & 11.0
  .github/workflows/dependencies/dependencies_nvcc11.sh
  .github/workflows/dependencies/dependencies_nvcc9.sh
  .github/workflows/linux.yml
Labels: GPU, test

#1669 CMake: dowstream projects must enable Fortran if AMReX_FORTRAN=ON
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/CMakeLists.txt
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXOptions.cmake
Labels: install

#1671 CI: OpenMP on Windows (Clang)
  .github/workflows/windows.yml
Labels: test

#1665 NVCC 11.2: CUDA/C++17
  .github/workflows/linux.yml
  Src/Particle/AMReX_NeighborList.H
  Src/Particle/AMReX_ParticleLocator.H
  Tutorials/GPU/CNS/Source/CNS.cpp
Labels: GPU, bug, help wanted, test
