Repository AMReX-Codes/amrex, pull requests merged in 2020-09, with the labels that each got.

#1287 CMake: re-write genex evaluation functions
  Tools/CMake/AMReXBuildInfo.cmake
  Tools/CMake/AMReXGenexHelpers.cmake
  Tools/CMake/AMReXInstallHelpers.cmake
  Tools/CMake/AMReXTargetHelpers.cmake
  Tools/CMake/AMReXTypecheck.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: install

#1336 CI: Move DPC++ dependencies
  .github/workflows/dependencies/dependencies_dpcpp.sh
  .github/workflows/linux.yml
Labels: test

#1352 Fallthrough: ICC Warning
  Src/Base/AMReX_Extension.H
Labels: warning

#1355 Docs: MPI_THREAD_MULTIPLE
  Docs/sphinx_documentation/source/BuildingAMReX.rst
Labels: documentation, install

#1351 Async IO: Check Runtime Threading
  Src/Base/AMReX_AsyncOut.cpp
  Src/Base/AMReX_ParallelDescriptor.H
  Src/Base/AMReX_ParallelDescriptor.cpp
Labels: bug

#1361 DPCPP Beta09: Package Broken
  .github/workflows/linux.yml
Labels: GPU, test

#1373 .gitignore: build/
  .gitignore
Labels: install

#1372 GNUMake: remove unused define for HIP compilation
  Tools/GNUMake/Make.defs
  Tools/GNUMake/comps/hip.mak
Labels: install

#1366 Re-Enable User defined literals in DPC++
  Src/Base/AMReX_REAL.H
  Tools/CMake/AMReXSYCL.cmake
  Tools/GNUMake/comps/dpcpp.mak
Labels: GPU, workaround

#1362 CMake: enable testing via CTest.
  .github/workflows/linux.yml
  CMakeLists.txt
  Tests/Algoim/CMakeLists.txt
  Tests/AsyncOut/multifab/CMakeLists.txt
  Tests/BBIOBenchmark/CMakeLists.txt
  Tests/BaseFabTesting/CMakeLists.txt
  Tests/CMakeLists.txt
  Tests/C_BaseLib/CMakeLists.txt
  Tests/DataServicesTest0/CMakeLists.txt
  Tests/FillBoundaryComparison/CMakeLists.txt
  Tests/Particles/NeighborParticles/CMakeLists.txt
  Tests/Particles/ParticleMesh/CMakeLists.txt
  Tests/Particles/ParticleReduce/CMakeLists.txt
  Tests/Particles/ParticleTransformations/CMakeLists.txt
  Tests/Particles/Redistribute/CMakeLists.txt
  Tests/complementIn/CMakeLists.txt
Labels: test

#1388 CMake & DPC++: Avoid Flag Deduplication
  .github/workflows/dependencies/dependencies_dpcpp.sh
  Tools/CMake/AMReXSYCL.cmake
Labels: install, workaround

#1391 Intall intel-oneapi-mkl-devel in CI
  .github/workflows/dependencies/dependencies_dpcpp.sh
Labels: GPU, test

#1402 CMake: enforce C++17 as minimum C++ standard for ENABLE_DPCPP=ON
  Tools/CMake/AMReX_Config.cmake
Labels: GPU, install

#1403 Docs: C++17 & Particle SP
  Docs/sphinx_documentation/source/BuildingAMReX.rst
Labels: documentation, install

#1404 DPCPP: use C++17 and disable mkl warnings
  Src/Base/AMReX_Random.H
  Src/Base/AMReX_RandomEngine.H
  Tools/GNUMake/comps/dpcpp.mak
Labels: GPU, install

#1406 ParallelDescriptor: Check MPI If Self
  Src/Base/AMReX_ParallelDescriptor.cpp
Labels: bug

#1421 Doc: update documentation on CMake+CUDA
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReX_SetupCUDA.cmake
Labels: GPU, documentation
