Repository AMReX-Codes/amrex, pull requests merged in 2021-08, with the labels that each got.

#2209 CMake: Prebuild & SetupCUDA
  Tools/CMake/AMReXConfig.cmake.in
Labels: install, warning

#2223 Test Build Variant
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXSetDefines.cmake
Labels: install, documentation

#2229 Parser: Noinline transcendental functions
  Src/Base/Parser/AMReX_Parser_Y.H
Labels: performance

#2217 Add sum(), product(), size(), {x,y,z}{lo,hi,len}() member functions to GpuArray and Array?D
  Src/Base/AMReX_Array.H
Labels: enhancement, GPU

#2242 Add definition of MLMG
  Docs/sphinx_documentation/source/LinearSolvers.rst
  Src/Base/AMReX_MultiFab.H
Labels: documentation

#2232 CI: Build Embedded Boundaries
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  Src/Base/AMReX_Slopes_K.H
  Src/EB/AMReX_EBMultiFabUtil_2D_C.H
  Src/EB/AMReX_EBMultiFabUtil_3D_C.H
  Src/EB/AMReX_EB_utils.cpp
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap_2D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap_3D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLNodeLaplacian_eb.cpp
  Tests/EB/CNS/Source/CNS.H
  Tests/EB_CNS/Source/hydro/CNS_divop_K.H
Labels: bug, test

#2250 Fix: Slopes K Literals
  Src/Base/AMReX_Slopes_K.H
Labels: bug, cleaning

#2251 Shorten CI tests and Enable CNS in CI
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  Tests/Amr/Advection_AmrCore/CMakeLists.txt
  Tests/Amr/Advection_AmrCore/Exec/inputs-ci
  Tests/Amr/Advection_AmrLevel/CMakeLists.txt
  Tests/Amr/Advection_AmrLevel/Exec/SingleVortex/inputs-ci
  Tests/Amr/Advection_AmrLevel/Exec/UniformVelocity/inputs-ci
  Tests/EB/CNS/CMakeLists.txt
  Tests/EB/CNS/Exec/Sod/inputs-ci
  Tests/EB_CNS/CMakeLists.txt
  Tests/EB_CNS/Exec/Combustor/inputs-ci
  Tests/GPU/CNS/CMakeLists.txt
  Tests/GPU/CNS/Exec/Sod/inputs-ci
  Tests/LinearSolvers/NodalPoisson/CMakeLists.txt
  Tests/LinearSolvers/NodalPoisson/inputs-ci
Labels: test

#2247 Make sure all ba are defined in test, and only call Init once per PC
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  Tests/Particles/GhostsAndVirtuals/main.cpp
Labels: bug, test

#2254 Github Action Concurrency
  .github/workflows/cuda.yml
  .github/workflows/docs.yml
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/style.yml
  .github/workflows/windows.yml
Labels: test

#2252 Fix Mixed Precision Particle CI Tests
  .github/workflows/linux.yml
  Src/AmrCore/AMReX_MFInterp_1D_C.H
  Src/Particle/AMReX_ParticleInit.H
  Tests/Particles/AssignDensity/main.cpp
  Tests/Particles/AssignMultiLevelDensity/main.cpp
  Tests/Particles/GhostsAndVirtuals/main.cpp
  Tests/Particles/ParallelContext/main.cpp
  Tests/Particles/ParticleMesh/main.cpp
  Tests/Particles/ParticleMeshMultiLevel/main.cpp
  Tests/Particles/ParticleReduce/main.cpp
Labels: bug

#2260 Fix #2256
  Src/Base/AMReX_FabArrayBase.H
  Src/Base/AMReX_FabArrayBase.cpp
  Src/Base/AMReX_MFParallelForG.H
Labels: bug, GPU

#2270 Fix FabArray move-ctor and move-=
  Src/Base/AMReX_FabArray.H
Labels: bug

#2296 Add gradient error tagging in Tests/Advection_AmrLevel
  Tests/Amr/Advection_AmrLevel/Source/AmrLevelAdv.cpp
Labels: enhancement, GPU

#2290 Add Docs for `fboxinfo`, `fcompare`, `fextract`, etc. to Post-Processing Tools
  Docs/sphinx_documentation/source/Post_Processing.rst
  Docs/sphinx_documentation/source/figs/ex_fsnapshot_resize.png
Labels: documentation
