Repository AMReX-Codes/amrex, pull requests merged in 2021-04, with the labels that each got.

#1918 Docs typo fix.
  Docs/sphinx_documentation/source/LinearSolvers_Chapter.rst
Labels: documentation

#1929 std::isfinite/inf for SYCL
  Src/Base/AMReX_Math.H
Labels: GPU

#1934 CMake: add support for BOUND_CHECK
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config.H.in
Labels: install

#1753 Fix out of bound error in AsyncWrite
  Src/Base/AMReX_VisMF.cpp
Labels: do not merge

#1959 CMake: implement logic to support compiler ID IntelLLVM (new in CMake 3.20)
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReXGenerateConfigHeader.cmake
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSYCL.cmake
Labels: GPU, install

#1964 Docs: CMake Multiple Archs
  Docs/sphinx_documentation/source/GPU.rst
Labels: GPU, documentation
