Repository AMReX-Codes/amrex, pull requests merged in 2021-01, with the labels that each got.

#1697 CI: Brew Returns Non-Zero If Already Installed
  .github/workflows/dependencies/dependencies_mac.sh
Labels: test, workaround

#1696 Support when CMake 3.18 policy 105 is set to new
  Tools/CMake/AMReX_Config.cmake
Labels: GPU, bug, install

#1701 CMake<3.18: Fix Linker Regression
  Tools/CMake/AMReX_Config.cmake
Labels: bug

#1727 CMake: link tests exes against alias library
  Tests/CMakeLists.txt
Labels: documentation, install

#1699 fix -Werror=sign-compare
  Src/Particle/AMReX_NeighborParticlesCPUImpl.H
  Src/Particle/AMReX_NeighborParticlesI.H
  Src/Particle/AMReX_StructOfArrays.H
Labels: warning

#1724 When using CMake 3.15 allow for MSVC runtime library changes
  Tools/CMake/AMReX_Config.cmake
Labels: install

#1732 Doc: Break into Debugger
  Docs/sphinx_documentation/source/Basics.rst
Labels: documentation

#1721 RoundRobin: option to not sort processes
  Src/Base/AMReX_DistributionMapping.H
  Src/Base/AMReX_DistributionMapping.cpp
Labels: bug

#1742 HIP: New Warp Size Macro
  Src/Base/AMReX_GpuDevice.H
Labels: GPU

#1752 Fix ParIter Ctor
  Src/Particle/AMReX_ParIter.H
Labels: bug
