Repository AMReX-Codes/amrex, pull requests merged in 2021-06, with the labels that each got.

#2064 HIP ROCTX: USE_RPATH Control
  Tools/GNUMake/comps/hip.mak
Labels: GPU, cleaning

#2061 GPU RDC Support
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/Base/AMReX.H
  Src/Base/AMReX.cpp
  Src/Base/AMReX_Arena.H
  Src/Base/AMReX_Random.H
  Src/Base/AMReX_Random.cpp
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXTargetHelpers.cmake
  Tools/GNUMake/Make.defs
  Tools/GNUMake/comps/hip.mak
  Tools/GNUMake/comps/nvcc.mak
  Tools/Plotfile/AMReX_PPMUtil.cpp
Labels: GPU, do not merge

#2074 CMake 3.20+ CUDA: Policy & Include
  CMakeLists.txt
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReXTargetHelpers.cmake
Labels: GPU, bug, install

#2076 Fix Plotfile Regression (introduced in #2063)
  Src/Particle/AMReX_WriteBinaryParticleData.H
Labels: bug

#2077 CMake CUDA: Filter out SM Before Pascal
  Tools/CMake/AMReXUtils.cmake
Labels: GPU, bug, install

#2079 Docs: RDC Option
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXOptions.cmake
Labels: documentation

#2081 AMReX_PROBINT: Depends on AMReX_AMRLEVEL
  Tools/CMake/AMReXOptions.cmake
Labels: install

#2084 Fix some macro issues in CMake Fortran build
  Src/AmrCore/AMReX_INTERP_2D.F90
  Src/AmrCore/AMReX_INTERP_3D.F90
  Src/Base/AMReX_FILCC_1D.F90
  Src/Base/AMReX_FILCC_2D.F90
  Src/Base/AMReX_FILCC_3D.F90
  Src/Base/AMReX_acc_mod.F90
  Src/Base/AMReX_filcc_mod.F90
  Src/Base/AMReX_fort_mod.F90
  Src/Base/AMReX_omp_mod.F90
  Src/Boundary/AMReX_LO_UTIL.F90
  Src/EB/AMReX_ebcellflag_mod.F90
  Src/F_Interfaces/AmrCore/AMReX_fillpatch_mod.F90
  Src/F_Interfaces/Base/AMReX_fab_mod.F90
  Src/F_Interfaces/Base/AMReX_parallel_mod.F90
  Src/F_Interfaces/Particle/AMReX_particlecontainer_mod.F90
  Src/LinearSolvers/MLMG/AMReX_MLLinOp_nd.F90
  Tests/FortranInterface/Advection_F/Source/compute_dt_mod.F90
  Tests/FortranInterface/Advection_F/Source/evolve_mod.F90
  Tests/FortranInterface/Advection_octree_F/Source/compute_dt_mod.F90
  Tests/FortranInterface/Advection_octree_F/Source/evolve_mod.F90
  Tools/CMake/AMReXSetDefines.cmake
Labels: Fortran, install, warning

#2093 CMake 3.20+ CUDA: Shell-Escape --Werror
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, bug, install

#2094 CMake 3.20+ CUDA: Fast Math
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, bug, install

#2096 CI: Split Linux Workflows
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/linux.yml
Labels: test

#2097 Particle Device Members: Inline
  Src/Particle/AMReX_Particle.H
Labels: cleaning

#2100 Add a number of forward declaration headers
  Src/Amr/AMReX_AmrFwd.H
  Src/Amr/CMakeLists.txt
  Src/Amr/Make.package
  Src/AmrCore/AMReX_AmrCoreFwd.H
  Src/AmrCore/CMakeLists.txt
  Src/AmrCore/Make.package
  Src/Base/AMReX_Array4.H
  Src/Base/AMReX_BaseFwd.H
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
  Src/Boundary/AMReX_BoundaryFwd.H
  Src/Boundary/CMakeLists.txt
  Src/Boundary/Make.package
Labels: enhancement

#2113 HIP: Increase to C++17
  .github/workflows/hip.yml
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReX_Config.cmake
  Tools/GNUMake/comps/hip.mak
Labels: GPU

#2116 Don't rely on managed memory in ParticleCopyPlan
  Src/Particle/AMReX_ParticleCommunication.H
  Src/Particle/AMReX_ParticleCommunication.cpp
Labels: GPU, bug
