Repository AMReX-Codes/amrex, pull requests merged in 2021-07, with the labels that each got.

#2031 CMake: HIP Modernizing & RDC
  .github/workflows/hip.yml
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, install

#2173 Fix warning with Intel icpc
  .github/workflows/intel.yml
  Src/Base/AMReX_Extension.H
Labels: warning

#2136 CI: IntelLLVM known to CMake
  .github/workflows/intel.yml
  Tools/CMake/AMReXSYCL.cmake
Labels: GPU, cleaning, install, test

#2186 CI: HIP Cleanup
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/hip.yml
Labels: GPU, cleaning, test
