Repository AMReX-Codes/amrex, pull requests merged in 2021-03, with the labels that each got.

#1831 CMake: AMReX_INSTALL
  CMakeLists.txt
  Docs/sphinx_documentation/source/BuildingAMReX.rst
Labels: install

#1833 AMReX Install: Config Header
  Tools/CMake/AMReXGenerateConfigHeader.cmake
Labels: install

#1840 CMake: move AMReX_INSTALL option to AMReXOptions.cmake
  CMakeLists.txt
  Tools/CMake/AMReXOptions.cmake
Labels: bug, install

#1846 AMREX_NO_PROBINIT
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/Amr/AMReX_Amr.H
  Src/Amr/AMReX_Amr.cpp
  Tools/CMake/AMReXGenerateConfigHeader.cmake
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config.H.in
  Tools/GNUMake/Make.defs
  Tools/libamrex/configure.py
Labels: do not merge

#1863 Fix CUDA API calls in host callback functions
  Src/Base/AMReX_CArena.cpp
Labels: bug

#1864 Fix bug in #1861
  Src/Base/AMReX_CArena.cpp
Labels: bug

#1836 CI: macOS Shared Lib
  .github/workflows/dependencies/dependencies_mac.sh
  .github/workflows/macos.yml
  Src/Amr/AMReX_LevelBld.H
  Src/Amr/AMReX_PROB_AMR_F.H
  Src/Base/AMReX_Extension.H
  Tools/CMake/AMReX_Config.cmake
Labels: bug, help wanted, install

#1867 Fix sign-compare and shadow warnings
  Src/Base/AMReX_NonLocalBC.H
  Src/Particle/AMReX_ParticleCommunication.H
  Src/Particle/AMReX_ParticleContainerI.H
Labels: warning

#1852 LevelBld
  Src/Amr/AMReX_Amr.H
  Src/Amr/AMReX_Amr.cpp
  Src/Amr/AMReX_LevelBld.H
  Tutorials/Amr/Advection_AmrLevel/Source/main.cpp
  Tutorials/EB/CNS/Source/main.cpp
  Tutorials/GPU/CNS/Source/main.cpp
  Tutorials/GPU/EBCNS/Source/main.cpp
Labels: do not merge

#1847 Build: Windows with Shared Libs (.dll)
  .github/workflows/windows.yml
  Src/AmrCore/AMReX_Interpolater.H
  Src/Base/AMReX.H
  Src/Base/AMReX_Extension.H
  Src/Base/AMReX_MFIter.H
  Src/Base/AMReX_ParallelContext.H
  Src/Base/AMReX_ParallelDescriptor.H
  Src/Base/AMReX_VisMF.H
  Src/EB/AMReX_EBInterpolater.H
  Src/Particle/AMReX_ParticleContainerBase.H
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReXTypecheck.cmake
  Tools/CMake/AMReX_Config.H.in
  Tools/CMake/AMReX_Config.cmake
  Tools/GNUMake/tools/Make.sensei
Labels: enhancement, install, test

#1880 Mask: -Wfinal-dtor-non-final-class
  Src/AmrCore/AMReX_TagBox.H
  Src/Boundary/AMReX_Mask.H
  Src/EB/AMReX_EBCellFlag.H
  Src/EB/AMReX_MultiCutFab.H
Labels: warning

#1879 Flags: RelWithDebInfo
  Tools/CMake/AMReXFlagsTargets.cmake
Labels: install, warning

#1890 CMake: IPO/LTO
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXBuildInfo.cmake
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXTypecheck.cmake
  Tools/CMake/AMReX_Config.cmake
Labels: install, performance

#1896 CI: HIP w/o MPI
  .github/workflows/linux.yml
Labels: GPU, test, workaround

#1897 CI: HIPCC as C Compiler
  .github/workflows/linux.yml
Labels: GPU, test

#1894 CMake: add test_install
  .github/workflows/linux.yml
  CMakeLists.txt
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tests/CMakeTestInstall/CMakeLists.txt
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: install, test
