Repository AMReX-Codes/amrex, pull requests merged in 2021-12, with the labels that each got.

#2448 AMREX_RELEASE_NUMBER
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReXUtils.cmake
  Tools/CMake/AMReX_Config.H.in
  Tools/GNUMake/Make.defs
Labels: install

#2500 Fix misleading documentation for ParticleTile.
  Docs/sphinx_documentation/source/Particle.rst
Labels: documentation

#2471 Use specific targets for make uninstall
  GNUmakefile.in
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.rules
Labels: install

#2475 CI: Run 2D and 1D Tests
  .github/workflows/gcc.yml
  Src/Particle/AMReX_ParticleInterpolators.H
  Src/Particle/CMakeLists.txt
  Src/Particle/Make.package
  Tests/AsyncOut/multifab/main.cpp
  Tests/LinearSolvers/NodalPoisson/CMakeLists.txt
  Tests/MultiBlock/Advection/CMakeLists.txt
  Tests/MultiBlock/Advection/main.cpp
  Tests/MultiBlock/IndexType/CMakeLists.txt
  Tests/MultiBlock/IndexType/main.cpp
  Tests/Particles/AssignDensity/main.cpp
  Tests/Particles/AsyncIO/main.cpp
  Tests/Particles/GhostsAndVirtuals/CMakeLists.txt
  Tests/Particles/InitFromAscii/CMakeLists.txt
  Tests/Particles/NeighborParticles/CheckPair.H
  Tests/Particles/NeighborParticles/MDParticleContainer.cpp
  Tests/Particles/ParallelContext/main.cpp
  Tests/Particles/ParticleIterator/main.cpp
  Tests/Particles/ParticleMesh/main.cpp
  Tests/Particles/ParticleMeshMultiLevel/main.cpp
  Tests/Particles/ParticleMeshMultiLevel/trilinear_deposition_K.H
  Tests/Particles/ParticleReduce/main.cpp
  Tests/Particles/ParticleTransformations/main.cpp
Labels: test

#2459 DPCPP: AMREX_INTEL_ARCH
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSYCL.cmake
Labels: GPU, install

#2525 CMake 3.22+: Policy CMP0127
  CMakeLists.txt
Labels: warning, install

#2477 Fix a bug in Robin BC
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.cpp
Labels: bug
