Repository AMReX-Codes/amrex, pull requests merged in 2021-09, with the labels that each got.

#2300 Change list of features to bullet list in Introduction.rst
  Docs/sphinx_documentation/source/Introduction.rst
Labels: documentation

#2321 CMake: Always CUDA Perf-Neutral Debug
  Tools/CMake/AMReXCUDAOptions.cmake
Labels: GPU, install

#2305 Amrvis doc revisions
  Docs/sphinx_documentation/source/Visualization.rst
Labels: documentation

#2303 Update Profiling API docs.
  Docs/sphinx_documentation/source/AMReX_Profiling_Tools.rst
Labels: documentation

#2340 Faq part one
  Docs/sphinx_documentation/source/Faq.rst
  Docs/sphinx_documentation/source/index.rst
Labels: documentation

#2355 CMake CUDA Debug: -G by Default
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXCUDAOptions.cmake
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, install

#2347 Port CellConservativeProtected::protect() to C++ with GPU support
  Src/AmrCore/AMReX_INTERP_2D.F90
  Src/AmrCore/AMReX_INTERP_3D.F90
  Src/AmrCore/AMReX_INTERP_F.H
  Src/AmrCore/AMReX_Interp_2D_C.H
  Src/AmrCore/AMReX_Interp_3D_C.H
  Src/AmrCore/AMReX_Interpolater.H
  Src/AmrCore/AMReX_Interpolater.cpp
Labels: GPU

#2363 CI: Split Linux
  .github/workflows/clang.yml
  .github/workflows/gcc.yml
  .github/workflows/sensei.yml
Labels: test

#2364 fix AmrMeshParticle cmake issue
  Src/Extern/SENSEI/CMakeLists.txt
Labels: bug, install

#2354 Gpu Comments to Doxygen Docs
  Src/Base/AMReX_GpuControl.H
  Src/Base/AMReX_GpuDevice.H
Labels: documentation

#2365 nvc++ w/ OMP: work-around atomic capture
  Src/Base/AMReX_FabArrayUtility.H
Labels: workaround

#2362 Port CellConservativeQuartic to C++ with GPU support
  Src/AmrCore/AMReX_INTERP_1D.F90
  Src/AmrCore/AMReX_INTERP_2D.F90
  Src/AmrCore/AMReX_INTERP_3D.F90
  Src/AmrCore/AMReX_INTERP_F.H
  Src/AmrCore/AMReX_Interp_1D_C.H
  Src/AmrCore/AMReX_Interp_2D_C.H
  Src/AmrCore/AMReX_Interp_3D_C.H
  Src/AmrCore/AMReX_Interpolater.H
  Src/AmrCore/AMReX_Interpolater.cpp
Labels: GPU

#2366 CI: Change HIP repo line to reflect latest changes
  .github/workflows/dependencies/dependencies_hip.sh
Labels: bug, test

#2066 CI: NVHPC for CUDA
  .github/workflows/cuda.yml
  .github/workflows/dependencies/dependencies_nvhpc21-9.sh
  Src/Base/AMReX_BLBackTrace.H
  Src/Base/AMReX_Extension.H
  Tools/CMake/AMReXGenerateConfigHeader.cmake
Labels: enhancement, help wanted, GPU

#2368 Update for oneapi 2021.4.0
  .github/workflows/intel.yml
  Src/Base/AMReX_FBI.H
  Src/Base/AMReX_GpuPrint.H
  Src/Base/AMReX_GpuQualifiers.H
  Src/Base/AMReX_GpuReduce.H
  Src/Base/AMReX_ParmParse.H
  Src/Base/AMReX_Scan.H
Labels: GPU
