Repository AMReX-Codes/amrex, pull requests merged in 2021-05, with the labels that each got.

#2029 Turn on RDC support for HIP
  Tools/GNUMake/comps/hip.mak
Labels: GPU, install

#2012 CMake: add support for CMake >= 3.20
  CMakeLists.txt
  Docs/sphinx_documentation/source/GPU.rst
  Src/CMakeLists.txt
  Tools/CMake/AMReXCUDAOptions.cmake
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReXGenexHelpers.cmake
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReXTargetHelpers.cmake
  Tools/CMake/AMReXUtils.cmake
  Tools/CMake/AMReX_Config.cmake
  Tools/CMake/AMReX_SetupCUDA.cmake
  Tools/CMake/AMReX_Utils.cmake
Labels: GPU, install

#2033 nvcc --display-error-number --diag-error errNum
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReX_SetupCUDA.cmake
  Tools/GNUMake/comps/nvcc.mak
Labels: GPU

#2028 Add spock support to GNU make
  Tools/GNUMake/Make.machines
  Tools/GNUMake/sites/Make.olcf
Labels: GPU, documentation

#2034 HIP: AMREX_AMD_ARCH Env Variable
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXOptions.cmake
Labels: GPU

#2043 ParamParse: Find Entries under Prefix
  Src/Base/AMReX_ParmParse.H
  Src/Base/AMReX_ParmParse.cpp
Labels: enhancement

#2025 Work-Around: oneAPI 2021.3.0 SYCL with oneDPL
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSYCL.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config.H.in
Labels: GPU, workaround

#2050 CMake link with roc::rocprim for HIP
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, bug, install

#2055 Link with HIP_LIBRARIES
  .github/workflows/linux.yml
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, bug, install

#2062 CMake: HIP Compiler - don't fail
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU

#2065 Set HIP_LIBRARIES before using
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, bug, install

#2067 CI: Cover Fortran
  .github/workflows/linux.yml
  Tests/CMakeTestInstall/CMakeLists.txt
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: test
