Repository AMReX-Codes/amrex, pull requests merged in 2022-05, with the labels that each got.

#2757 CUDA On Cray: More Robust w/o Wrapper
  Tools/CMake/AMReXParallelBackends.cmake
Labels: bug, GPU, install

#2753 Add HDF5 H5Z-ZFP support in CMake
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReXThirdPartyLibraries.cmake
  Tools/CMake/AMReX_Config.H.in
Labels: enhancement, install

#2773 Fix: AmrCore Move
  Src/AmrCore/AMReX_AmrCore.H
  Src/AmrCore/AMReX_AmrCore.cpp
  Src/AmrCore/AMReX_AmrParGDB.H
Labels: bug

#2771 CI--HIP: wget gpg key from https instead of http
  .github/workflows/dependencies/dependencies_hip.sh
Labels: test

#2770 Pass value of AMReX_GPU_RDC flag to CMake find_package(AMReX ... )
  Tools/CMake/AMReXConfig.cmake.in
Labels: GPU, install

#2790 Fix compiler warnings in debug mode for integrator
  Src/Base/AMReX_TimeIntegrator.H
Labels: warning

#2793 Implement Serial ParallelDescriptor::Gather
  Src/Base/AMReX_ParallelDescriptor.H
Labels: bug

#2777 [Docs] Move 'Example Codes' section under 'Getting Started'
  Docs/sphinx_documentation/source/Basics.rst
  Docs/sphinx_documentation/source/EB.rst
  Docs/sphinx_documentation/source/EB_Chapter.rst
  Docs/sphinx_documentation/source/GPU.rst
  Docs/sphinx_documentation/source/GettingStarted.rst
Labels: documentation

#2795 CI: Fix HIP GPG Key
  .github/workflows/dependencies/dependencies_hip.sh
Labels: GPU, test, workaround

#2796 Fix document on MultiFab reduction
  Docs/sphinx_documentation/source/GPU.rst
Labels: documentation
