Repository AMReX-Codes/amrex, pull requests merged in 2022-12, with the labels that each got.

#3008 Add math functions to amrex::Math
  Src/Base/AMReX_Math.H
Labels: enhancement

#3049 Add PETSc CI
  .github/workflows/petsc.yml
Labels: enhancement

#3057 Fix: Shared CMake builds w/ `AMReX_BUILD_SHARED_LIBS`
  Src/CMakeLists.txt
Labels: bug, install

#3059 Add CodeQL Scanning
  .github/workflows/codeql.yml
Labels: test

#3078 CI: Ascent
  .github/workflows/ascent.yml
  .github/workflows/sensei.yml
Labels: test

#3076 amrex::fillAsync
  Src/Base/AMReX_GpuContainers.H
Labels: performance, GPU
