Repository AMReX-Codes/amrex, pull requests merged in 2022-10, with the labels that each got.

#2983 MFIter::Finalize
  Src/Base/AMReX_MFIter.H
  Src/Base/AMReX_MFIter.cpp
Labels: enhancement

#2985 MFIter: Make Finalize Public
  Src/Base/AMReX_MFIter.H
  Src/Base/AMReX_MFIter.cpp
Labels: enhancement

#2988 `MFIter::Finalize`: Free `m_fa`
  Src/Base/AMReX_MFIter.cpp
Labels: bug

#2990 CMake Docs: Fix User-Guidance (Link)
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Docs/sphinx_documentation/source/GPU.rst
Labels: documentation

#2954 ParallelFor with compile time optimization of kernels with run time parameters
  Src/Base/AMReX_CTOParallelForImpl.H
  Src/Base/AMReX_GpuLaunch.H
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
  Tests/CMakeLists.txt
  Tests/CTOParFor/CMakeLists.txt
  Tests/CTOParFor/GNUmakefile
  Tests/CTOParFor/Make.package
  Tests/CTOParFor/main.cpp
Labels: enhancement, performance, GPU

#2991 Pre- and Post-interpolation hook interface
  Src/AmrCore/AMReX_FillPatchUtil_I.H
  Src/AmrCore/AMReX_FillPatcher.H
Labels: do not merge

#2998 Make The_Device_Arena non-managed
  Src/Base/AMReX_Arena.cpp
  Src/Base/AMReX_GpuContainers.H
Labels: performance, GPU

#2997 `FabArray::isDefined`
  Src/Base/AMReX_FabArray.H
Labels: enhancement
