Repository AMReX-Codes/amrex, pull requests merged in 2022-09, with the labels that each got.

#2936 Fix ParmParse: Loading Files Again
  Src/Base/AMReX_ParmParse.H
  Src/Base/AMReX_ParmParse.cpp
Labels: bug

#2932 HIP: use coarse grained host memory
  Src/Base/AMReX_Arena.cpp
Labels: performance, GPU

#2933 Link to cublas when using CUDA and Hypre
  Src/LinearSolvers/OpenBC/AMReX_OpenBC.cpp
  Tools/GNUMake/packages/Make.hypre
Labels: install

#2944 Fix: Make Finalize->Initialize->F->I->... Work
  Src/Base/AMReX_Arena.cpp
Labels: bug

#2948 CMake: HIP_PATH from ROCM_PATH
  .github/workflows/hip.yml
  Src/Base/AMReX_GpuDevice.cpp
  Src/Base/AMReX_TinyProfiler.H
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/GNUMake/comps/hip.mak
Labels: GPU, install

#2950 Add roundoff_lo corresponding to roundoff_hi for domains that don't start at 0
  Src/Base/AMReX_Geometry.H
  Src/Base/AMReX_Geometry.cpp
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleUtil.H
Labels: bug

#2963 Fix MLEBNodeFDLaplacian bottom solver
  Src/LinearSolvers/MLMG/AMReX_MLEBNodeFDLaplacian.H
Labels: bug
