Repository AMReX-Codes/amrex, pull requests merged in 2022-01, with the labels that each got.

#2577 HIP: Add -munsafe-fp-atomics to CMake
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, install, workaround

#2582 HIP: amdclang++
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, warning, install

#2575 `add_par` precendence correction in Docs.
  Docs/sphinx_documentation/source/Basics.rst
Labels: documentation

#2595 CI: AMD `hip::device` also for Fortran
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/hip.yml
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, install, cleaning

#2583 Update locations for tutorials and minor formatting.
  Docs/sphinx_documentation/source/Fortran.rst
  Docs/sphinx_documentation/source/GPU.rst
  Docs/sphinx_documentation/source/GettingStarted.rst
  Docs/sphinx_documentation/source/LinearSolvers.rst
  Docs/sphinx_documentation/source/Testing.rst
  Docs/sphinx_documentation/source/Visualization.rst
Labels: documentation

#2598 Disable EB solver's phi-on-centroid for hip for now
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap_F.cpp
Labels: GPU, workaround
