Repository AMReX-Codes/amrex, pull requests merged in 2022-03, with the labels that each got.

#1809 HIP: atomicAddNoRet
  Src/Base/AMReX_GpuAtomic.H
Labels: do not merge

#2642 Simplify CoordSys::IsRZ and IsSPHERICAL
  Src/Base/AMReX_CoordSys.H
Labels: enhancement

#2629 Update SpackSmokeTest to run with Fortran and/or HIP.
  Tests/SpackSmokeTest/CMakeLists.txt
Labels: GPU, install, test

#2650 AMReX_Config.H: AMREX_EXPORT_DYNAMIC
  Tools/CMake/AMReX_Config.H.in
Labels: bug, install

#2653 Introduce `AMReX_Version.H`
  Src/Base/AMReX.H
  Src/Base/AMReX.cpp
  Src/Base/AMReX_Version.cpp
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
  Tools/CMake/AMReXGenerateConfigHeader.cmake
  Tools/CMake/AMReX_Config.H.in
  Tools/CMake/AMReX_Version.H.in
  Tools/GNUMake/Make.defs
  Tools/GNUMake/Make.rules
  Tools/libamrex/mkversionheader.py
Labels: bug, install

#2665 FluxRegister: Fix warnings
  Src/AmrCore/AMReX_FluxRegister.cpp
  Tools/CMake/AMReX_Config.H.in
Labels: warning

#2659 Doc: AMReX_TP_PROFILE
  Docs/sphinx_documentation/source/BuildingAMReX.rst
Labels: install, documentation

#2673 Redefine ParticleContainter multifab after setting particle boxarray and dmap
  Src/Particle/AMReX_ParticleContainerBase.cpp
Labels: bug

#2676 MPI+OMP+HIP build capability
  Tools/CMake/AMReX_Config.H.in
  Tools/GNUMake/comps/hip.mak
  Tools/libamrex/mkconfig.py
Labels: enhancement, install

#2677 Catch CUDA 11.6 bug at compile time
  Src/Base/AMReX_BCUtil.cpp
  Src/Base/AMReX_PhysBCFunct.H
Labels: bug, wontfix, GPU, workaround

#2672 CI: Apple Silicon
  .github/workflows/macos.yml
  Src/Base/AMReX.cpp
Labels: test

#2687 CI: NVHPC New Apt Repo
  .github/workflows/cuda.yml
  .github/workflows/dependencies/dependencies_nvhpc21-11.sh
  .github/workflows/dependencies/dependencies_nvhpc21-9.sh
Labels: GPU, test
