Repository AMReX-Codes/amrex, pull requests merged in 2023-09, with the labels that each got.

#3528 Fix: Include Guard 1D for MLPoisson
  Src/LinearSolvers/MLMG/AMReX_MLPoisson_1D_K.H
Labels: bug

#3523 Add ability for GCC 8 in CMake to build fgradient which uses std::filesystem
  Tools/CMake/FindFilesystem.cmake
  Tools/Plotfile/CMakeLists.txt
Labels: install

#3527 Fix InitRandomPerBox for 1D & 2D
  Src/Base/AMReX_RealBox.H
  Src/Particle/AMReX_ParticleInit.H
Labels: bug

#3546 FillPatch Fortran Interface: Fix incorrect size of Vector<BCRec>
  Src/F_Interfaces/AmrCore/AMReX_fillpatch_fi.cpp
Labels: bug

#3440 ParmParse::addfile needs Init
  Src/Base/AMReX_ParmParse.cpp
Labels: enhancement

#3290 PureSoA: Disable AoS Access
  Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleInit.H
  Src/Particle/AMReX_ParticleTile.H
  Tests/Particles/RedistributeSOA/main.cpp
  Tests/Particles/SENSEI_Insitu_SOA/main.cpp
Labels: bug, enhancement
