Repository AMReX-Codes/amrex, pull requests merged in 2023-10, with the labels that each got.

#3568 Fix Boundary Centroid in a Corner Case in 2D
  Src/EB/AMReX_EB2_2D_C.cpp
Labels: bug, do not merge

#3582 Docs: Link pyAMReX
  Docs/sphinx_documentation/source/Python_Chapter.rst
  Docs/sphinx_documentation/source/index.rst
Labels: documentation

#3583 Fix ICC CI by Freeing up Disk Space
  .github/workflows/intel.yml
Labels: test

#3566 Disable CCache in Windows CIs
  .github/workflows/cleanup-cache.yml
  .github/workflows/windows.yml
Labels: test

#3589 RealVect Static: Export
  Src/Base/AMReX_RealVect.H
Labels: bug

#3592 Fix a memory "leak" in VisMF's persistent streams
  Src/Base/AMReX_VisMF.cpp
  Src/Base/AMReX_VisMFBuffer.H
Labels: bug

#3594 Fix Assertion in MLEBNodeFDLaplacian
  Src/LinearSolvers/MLMG/AMReX_MLEBNodeFDLaplacian.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeLaplacian_sten.cpp
  Src/LinearSolvers/MLMG/AMReX_MLNodeLinOp.H
Labels: bug

#3599 Install Move Tools to `shared/amrex`
  Tools/CMake/AMReXBuildInfo.cmake
  Tools/CMake/AMReXInstallHelpers.cmake
  Tools/CMake/AMReXTypecheck.cmake
Labels: install

#3606 Windows: Fix Installed AMReXBuildInfo.cmake
  Tools/CMake/AMReXBuildInfo.cmake
Labels: bug, install

#3609 `AMReXBuildInfo.cmake`: AMReX_DIR
  Tools/CMake/AMReXBuildInfo.cmake
Labels: bug, install
