Repository AMReX-Codes/amrex, pull requests merged in 2023-01, with the labels that each got.

#3086 Update CHANGES for 23.01
  CHANGES
Labels: documentation

#2640 Mlebabeclap aniso
  Src/Base/AMReX_SPACE.H
  Src/EB/AMReX_EB2_2D_C.cpp
  Src/EB/AMReX_EB2_C.H
  Src/EB/AMReX_EB2_Level.H
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap.cpp
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap_2D_K.H
  Src/LinearSolvers/MLMG/AMReX_MLEBABecLap_F.cpp
Labels: enhancement

#3093 CMake: Make hypre and PETSc available only if it's not 1D.
  Tools/CMake/AMReXOptions.cmake
Labels: install

#3061 CI: Doxygen
  .github/workflows/style.yml
  .github/workflows/style/doxygen.sh
  Docs/Doxygen/doxygen.conf
  Src/Amr/AMReX_AuxBoundaryData.cpp
  Src/AmrCore/AMReX_ErrorList.cpp
  Src/Base/AMReX_DistributionMapping.cpp
  Src/Base/AMReX_FabArrayCommI.H
  Src/Base/AMReX_GpuReduce.H
  Src/Base/AMReX_ParmParse.H
  Src/Base/AMReX_Random.cpp
  Src/Base/AMReX_Utility.H
Labels: documentation

#3094 SinCos: AppleClang Fix
  Src/Base/AMReX_Math.H
Labels: bug

#3096 SinCos Guard: Apple Define
  Src/Base/AMReX_Math.H
Labels: bug

#3099 CI: actions/checkout@v3
  .github/workflows/ascent.yml
  .github/workflows/style.yml
Labels: warning, test

#3108 Replace sprintf with snprintf to fix compiler warnings
  Tests/HDF5Benchmark/main.cpp
  Tests/Particles/CheckpointRestart/main.cpp
Labels: bug

#3100 CMake clean up
  .github/workflows/dependencies/dependencies_dpcpp.sh
  .github/workflows/intel.yml
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/EB/CMakeLists.txt
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReXSYCL.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReXUtils.cmake
Labels: install

#3112 CMake 3.18+: Stay OLD CUDA_ARCHITECTURES Policy
  CMakeLists.txt
  Tools/CMake/AMReXUtils.cmake
Labels: bug, GPU, install
