Repository AMReX-Codes/amrex, pull requests merged in 2023-04, with the labels that each got.

#3230 CI: CMake-Easyinstall Unused
  .github/workflows/dependencies/dependencies_hip.sh
Labels: test, cleaning

#3220 Fix: queryAdd for resizing vectors
  Src/Base/AMReX_ParmParse.H
Labels: bug, help wanted

#3239 CI: oneAPI -Wmissing-braces
  .github/workflows/intel.yml
Labels: GPU, test, workaround

#3225 Support complete elliptic integrals of 1st and 2nd type in Parser
  Docs/sphinx_documentation/source/Basics.rst
  Src/Base/Parser/AMReX_Parser_Y.H
  Src/Base/Parser/AMReX_Parser_Y.cpp
  Src/Base/Parser/amrex_iparser.lex.cpp
  Src/Base/Parser/amrex_iparser.lex.h
  Src/Base/Parser/amrex_iparser.lex.nolint.H
  Src/Base/Parser/amrex_iparser.tab.h
  Src/Base/Parser/amrex_iparser.tab.nolint.H
  Src/Base/Parser/amrex_parser.l
  Src/Base/Parser/amrex_parser.lex.cpp
  Src/Base/Parser/amrex_parser.lex.h
  Src/Base/Parser/amrex_parser.lex.nolint.H
  Src/Base/Parser/amrex_parser.tab.h
  Src/Base/Parser/amrex_parser.tab.nolint.H
Labels: enhancement

#3242 CI: Retry Apt Repos
  .github/workflows/dependencies/dependencies.sh
  .github/workflows/dependencies/dependencies_clang-tidy.sh
  .github/workflows/dependencies/dependencies_clang.sh
  .github/workflows/dependencies/dependencies_dpcpp.sh
  .github/workflows/dependencies/dependencies_gcc.sh
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/dependencies/dependencies_nofortran.sh
  .github/workflows/dependencies/dependencies_nvcc11.sh
  .github/workflows/dependencies/dependencies_nvcc12.sh
  .github/workflows/dependencies/dependencies_nvhpc.sh
  .github/workflows/dependencies/documentation.sh
Labels: test

#3245 ParticleTileData: No Restrict in Storage
  Src/Particle/AMReX_ParticleTile.H
Labels: enhancement

#3247 Fix Roundoff Domain
  Src/Base/AMReX_Geometry.cpp
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleUtil.H
Labels: bug

#3248 Add Tests/RoundoffDomain
  Src/Base/AMReX_Geometry.cpp
  Src/Particle/AMReX_ParticleUtil.H
  Tests/CMakeLists.txt
  Tests/RoundoffDomain/CMakeLists.txt
  Tests/RoundoffDomain/GNUmakefile
  Tests/RoundoffDomain/Make.package
  Tests/RoundoffDomain/main.cpp
Labels: bug, test

#2878 Support SoA-Only Particles
  Src/AmrCore/AMReX_AmrParticles.H
  Src/Base/AMReX_Array.H
  Src/Base/AMReX_Geometry.H
  Src/Base/AMReX_TypeTraits.H
  Src/EB/AMReX_EB2.H
  Src/Extern/HDF5/AMReX_ParticleHDF5.H
  Src/Particle/AMReX_ArrayOfStructs.H
  Src/Particle/AMReX_MakeParticle.H
  Src/Particle/AMReX_ParIter.H
  Src/Particle/AMReX_Particle.H
  Src/Particle/AMReX_ParticleCommunication.H
  Src/Particle/AMReX_ParticleContainer.H
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleIO.H
  Src/Particle/AMReX_ParticleInit.H
  Src/Particle/AMReX_ParticleTile.H
  Src/Particle/AMReX_ParticleTransformation.H
  Src/Particle/AMReX_ParticleUtil.H
  Src/Particle/AMReX_WriteBinaryParticleData.H
  Src/Particle/CMakeLists.txt
  Src/Particle/Make.package
  Tests/Particles/ParticleTransformations/main.cpp
  Tests/Particles/RedistributeSOA/CMakeLists.txt
  Tests/Particles/RedistributeSOA/GNUmakefile
  Tests/Particles/RedistributeSOA/Make.package
  Tests/Particles/RedistributeSOA/inputs
  Tests/Particles/RedistributeSOA/inputs.rt
  Tests/Particles/RedistributeSOA/inputs.rt.cuda
  Tests/Particles/RedistributeSOA/inputs.rt.cuda.big
  Tests/Particles/RedistributeSOA/inputs.rt.cuda.mr
  Tests/Particles/RedistributeSOA/inputs.rt.cuda.nonperiodic
  Tests/Particles/RedistributeSOA/inputs.rt.cuda.sort
  Tests/Particles/RedistributeSOA/main.cpp
  Tests/Particles/SOAParticle/CMakeLists.txt
  Tests/Particles/SOAParticle/main.cpp
Labels: enhancement, performance

#3260 Conduit: Update ParticleTile API
  Src/Extern/Conduit/AMReX_Conduit_Blueprint_ParticlesI.H
Labels: bug

#3262 Fix default template parameter for ParConstIter
  Src/Particle/AMReX_ParIter.H
Labels: bug

#3270 Doc: Real/ParticleReal Doxygen
  Src/Base/AMReX_REAL.H
Labels: documentation

#3274 CMake: Fix CUDA Options Order
  CMakeLists.txt
Labels: bug, GPU, install

#3277 Update SortParticlesForDeposition for pure SoA
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleTile.H
  Src/Particle/AMReX_ParticleUtil.H
Labels: bug, enhancement

#3275 Work-Around: CUDA 12.1 Non-Default Codelines
  Tools/CMake/AMReXCUDAOptions.cmake
Labels: GPU, workaround

#3278 Implement increment for pure SoA
  Src/Particle/AMReX_ParticleContainerI.H
Labels: bug, enhancement

#3283 Fix RealVect version of pos() for pure SoA
  Src/Particle/AMReX_ParticleTile.H
Labels: bug

#3284 Fix increment for pure SoA (follow on to #3278)
  Src/Particle/AMReX_ParticleContainerI.H
Labels: bug
