Repository AMReX-Codes/amrex, pull requests merged in 2023-07, with the labels that each got.

#3439 Doxygen: SoA Get[Real/Int]Data
  Src/Particle/AMReX_StructOfArrays.H
Labels: documentation

#3429 SYCL RelWithDebInfo Build: Add -g1
  Tools/CMake/AMReXFlagsTargets.cmake
Labels: GPU, install

#3438 Disable Managed Memory for The_Arena by default.
  Docs/sphinx_documentation/source/GPU.rst
  Src/Base/AMReX_Arena.cpp
Labels: performance, GPU

#3445 PODVector: Add a Missing STL Include
  Src/Base/AMReX_PODVector.H
Labels: bug

#3382 GPU Assignment
  Docs/sphinx_documentation/source/GPU.rst
  Src/Base/AMReX_GpuDevice.cpp
  Src/Base/AMReX_ParallelDescriptor.H
  Src/Base/AMReX_ParallelDescriptor.cpp
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config_ND.H.in
  Tools/GNUMake/Make.defs
  Tools/GNUMake/sites/Make.alcf
  Tools/GNUMake/sites/Make.llnl
  Tools/GNUMake/sites/Make.nersc
  Tools/GNUMake/sites/Make.nrel
  Tools/GNUMake/sites/Make.olcf
Labels: GPU

#3349 SENSEI: SoA Particle Support
  Src/Extern/SENSEI/AMReX_AmrMeshParticleDataAdaptor.H
  Src/Extern/SENSEI/AMReX_AmrMeshParticleDataAdaptorI.H
  Src/Extern/SENSEI/AMReX_AmrMeshParticleInSituBridge.H
  Src/Extern/SENSEI/AMReX_AmrParticleDataAdaptor.H
  Src/Extern/SENSEI/AMReX_AmrParticleDataAdaptorI.H
  Src/Extern/SENSEI/AMReX_AmrParticleInSituBridge.H
  Src/Extern/SENSEI/AMReX_ParticleDataAdaptor.H
  Src/Extern/SENSEI/AMReX_ParticleDataAdaptorI.H
  Src/Extern/SENSEI/AMReX_ParticleInSituBridge.H
  Tests/CMakeLists.txt
  Tests/Particles/SENSEI_Insitu_SOA/CMakeLists.txt
  Tests/Particles/SENSEI_Insitu_SOA/GNUmakefile
  Tests/Particles/SENSEI_Insitu_SOA/inputs.rt
  Tests/Particles/SENSEI_Insitu_SOA/main.cpp
Labels: enhancement

#3447 Mac Arm64 Architecture fpe handling
  Docs/sphinx_documentation/source/Debugging.rst
  Src/Base/AMReX.cpp
  Src/Base/AMReX_BLBackTrace.cpp
  Tools/CMake/AMReXFlagsTargets.cmake
Labels: enhancement
