Repository AMReX-Codes/amrex, pull requests merged in 2023-08, with the labels that each got.

#3446 PlotFileUtil: Add Direct Includes
  Src/Base/AMReX_PlotFileUtil.H
Labels: cleaning

#3465 Fix a bug in EB tensor solver's cross term
  Src/LinearSolvers/MLMG/AMReX_MLEBTensor_3D_K.H
Labels: bug

#3485 Fix a bug in #3466
  Src/Base/AMReX_Array.H
Labels: bug

#3489 Fix overflow in ParallelFor(Long n, ...)
  Src/Base/AMReX_GpuLaunch.H
Labels: bug

#3487 CMake: HIP Debug with -O1
  Tools/CMake/AMReXParallelBackends.cmake
Labels: GPU, install, workaround

#3387 CI: Remove redundancy in nvcc dependencies files
  .github/workflows/cuda.yml
  .github/workflows/dependencies/dependencies_llvm_cuda11_clang15.sh
  .github/workflows/dependencies/dependencies_llvm_cuda11_ubuntu22.sh
  .github/workflows/dependencies/dependencies_nvcc.sh
  .github/workflows/dependencies/dependencies_nvcc11.sh
  .github/workflows/hypre.yml
  .github/workflows/intel.yml
  .github/workflows/sundials.yml
Labels: GPU, install

#3502 Fix: Backtraces will NULL Addresses
  Src/Base/AMReX_BLBackTrace.cpp
Labels: bug

#3505 Fix backtrace nullptrs
  Src/Base/AMReX_BLBackTrace.cpp
Labels: bug

#3483 Fix Bug in FaceLinear Interpolater
  Src/AmrCore/AMReX_Interp_2D_C.H
  Src/AmrCore/AMReX_Interp_3D_C.H
  Src/AmrCore/AMReX_Interpolater.cpp
Labels: bug

#3510 Simplify filterParticles Kernel
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleTransformation.H
Labels: bug, GPU, workaround

#3520 UniqueString tweak
  Src/Base/AMReX_Utility.cpp
Labels: bug, enhancement
