Repository AMReX-Codes/amrex, pull requests merged in 2023-12, with the labels that each got.

#3585 Pure SoA Particle: Separate Array for IdCPU
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleIO.H
  Src/Particle/AMReX_ParticleInit.H
  Src/Particle/AMReX_ParticleTile.H
  Src/Particle/AMReX_ParticleTransformation.H
  Src/Particle/AMReX_StructOfArrays.H
  Src/Particle/AMReX_WriteBinaryParticleData.H
  Tests/Particles/RedistributeSOA/main.cpp
Labels: help wanted, performance

#3661 Fix SuperParticle `push_back`
  Src/Particle/AMReX_ParticleTile.H
Labels: bug

#3622 Documentation for Profiling: Hot Spots and Load Balance
  Docs/sphinx_documentation/source/AMReX_Profiling_Tools.rst
Labels: documentation

#3628 CMake: AMReX_PARALLEL_LINK_JOBS
  .github/workflows/intel.yml
  Docs/sphinx_documentation/source/GPU.rst
  Tools/CMake/AMReXFlagsTargets.cmake
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXSYCL.cmake
Labels: install

#3671 PureSoA IdCpu fixes
  Src/Particle/AMReX_Particle.H
  Src/Particle/AMReX_ParticleTile.H
  Src/Particle/AMReX_StructOfArrays.H
Labels: bug
