Repository AMReX-Codes/amrex, pull requests merged in 2024-02, with the labels that each got.

#3735 Add `ParticleIDWrapper::make_invalid()`
  Src/Particle/AMReX_Particle.H
Labels: performance

#3743 Add partitionParticles Function
  Src/Particle/AMReX_ParticleUtil.H
Labels: enhancement

#3740 Revert "Disable SYCL on Nvidia and AMD CIs (#3726)"
  .github/workflows/dependencies/dependencies_codeplay.sh
  .github/workflows/intel.yml
Labels: test

#3772 Pure SoA: `NextID` as `Long`
  Src/Particle/AMReX_ParticleTile.H
Labels: bug
