Repository AMReX-Codes/amrex, pull requests merged in 2024-06, with the labels that each got.

#3965 adding physical and math BC types for inflow-outflow BCs
  Src/Base/AMReX_BC_TYPES.H
Labels: do not merge

#3951 Skip empty particle tiles in operator++ to avoid race condition in constructor.
  Src/Particle/AMReX_ParIter.H
  Src/Particle/AMReX_ParticleContainerI.H
Labels: do not merge

#3977 Add structured binding support to GpuTuple
  Src/Base/AMReX_Tuple.H
Labels: enhancement

#3980 use HIP stream-ordered allocator
  Src/Base/AMReX_GpuControl.H
  Src/Base/AMReX_GpuDevice.cpp
  Src/Base/AMReX_PArena.H
  Src/Base/AMReX_PArena.cpp
Labels: enhancement, GPU

#3978 Add TupleSplit
  Src/Base/AMReX_Tuple.H
Labels: enhancement
