Repository AMReX-Codes/amrex, pull requests merged in 2024-09, with the labels that each got.

#4116 `AMREX_DEVICE_PRINTF`: Host
  Src/Base/AMReX_GpuPrint.H
Labels: bug

#4129 MLMG: Minimum domain width
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLLinOp.H
Labels: enhancement, performance

#4126 `ParmParse`: Prefix to `FILE`
  Src/Base/AMReX_ParmParse.H
  Src/Base/AMReX_ParmParse.cpp
Labels: enhancement

#4143 AMREX_ENUM: Add more capabilites
  Src/Base/AMReX_Enum.H
  Tests/Enum/main.cpp
Labels: enhancement

#4145 Add ParmParse::query_enum_sloppy that can ignore characters
  Src/Base/AMReX_ParmParse.H
  Tests/Enum/inputs
  Tests/Enum/main.cpp
Labels: enhancement

#4156 `ParmParse:addFile`: User-Friendly Error
  Src/Base/AMReX_ParmParse.cpp
Labels: enhancement

#4164 Deregister BArena from Profiling in Arena::Finalize
  Src/Base/AMReX_Arena.H
  Src/Base/AMReX_Arena.cpp
Labels: bug
