Repository AMReX-Codes/amrex, pull requests merged in 2024-03, with the labels that each got.

#3783 Fix GPU restart for pure SoA particles
  Src/Particle/AMReX_ParticleIO.H
  Src/Particle/AMReX_WriteBinaryParticleData.H
Labels: bug, GPU

#3782 Update CHANGES for 24.03
  CHANGES
Labels: documentation

#3796 `omp_locks`: C Array
  Src/Base/AMReX_OpenMP.H
  Src/Base/AMReX_OpenMP.cpp
Labels: bug

#3798 omp_locks: Avoid extern global variable
  Src/Base/AMReX_BaseFab.H
  Src/Base/AMReX_OpenMP.H
  Src/Base/AMReX_OpenMP.cpp
Labels: bug

#3804 CI: Windows MSVC w/ Ninja
  .github/workflows/windows.yml
Labels: bug, test

#3805 Add Tests/OpenMP/atomicAdd
  Tests/CMakeLists.txt
  Tests/OpenMP/atomicAdd/CMakeLists.txt
  Tests/OpenMP/atomicAdd/GNUmakefile
  Tests/OpenMP/atomicAdd/Make.package
  Tests/OpenMP/atomicAdd/main.cpp
Labels: test

#3803 CI: Windows Install & Test Install
  .github/workflows/windows.yml
  Tests/CMakeTestInstall/CMakeLists.txt
  Tools/CMake/AMReXInstallHelpers.cmake
Labels: test

#3802 Explicit Includes: MultiFab -> BaseFab
  Src/Base/AMReX_FabArray.H
  Src/Base/AMReX_FabArrayBase.H
  Src/Base/AMReX_MultiFab.H
Labels: cleaning

#3807 Fix a memory leak in TableData::operator=
  Src/Base/AMReX_TableData.H
Labels: bug

#3825 Clang-Tidy 17: cppcoreguidelines-rvalue-reference-param-not-moved
  Src/Base/AMReX_Any.H
  Src/Base/AMReX_BoxArray.cpp
  Src/Base/AMReX_GpuElixir.H
  Src/Base/AMReX_PODVector.H
  Src/Base/AMReX_ParallelDescriptor.H
  Src/Base/AMReX_ParallelDescriptor.cpp
  Src/Base/AMReX_VisMF.cpp
Labels: performance

#3847 Minor documentation clarification.
  Docs/sphinx_documentation/source/Basics.rst
Labels: documentation

#3856 `FabArray<FAB>::copy` Argument Name
  Src/Base/AMReX_FabArray.H
Labels: cleaning

#3848 `MultiFab::deepCopy()`
  Src/Base/AMReX_MultiFab.H
  Src/Base/AMReX_MultiFab.cpp
Labels: enhancement

#3615 `AddRealComp`/`AddIntComp`: Resize SoA
  Src/Particle/AMReX_ParticleContainer.H
Labels: enhancement

#3861 Fix: Resize Component on Add
  Src/Particle/AMReX_ParticleContainer.H
Labels: bug
