Repository AMReX-Codes/amrex, pull requests merged in 2024-05, with the labels that each got.

#3917 Add GOVERNANCE.rst, based on the WarpX model
  Docs/sphinx_documentation/source/Governance.rst
  Docs/sphinx_documentation/source/index.rst
  GOVERNANCE.rst
Labels: documentation

#3931 Update development team
  Docs/Doxygen/main.dox
  Docs/sphinx_documentation/source/Introduction.rst
  Docs/sphinx_documentation/source/index.rst
  README.md
Labels: documentation

#3936 Amend Notices for Non-Endorsement
  NOTICE
  README.md
Labels: documentation

#3939 Fix 1d HDF5 compilation
  Src/Extern/HDF5/AMReX_ParticleHDF5.H
Labels: bug

#3915 CTest: Add atomicAdd to small tests
  Tests/CMakeLists.txt
Labels: test

#3947 CMake: No Deprecation Warnings
  CMakeLists.txt
Labels: warning, install

#3910 Workaround for Windows omp_lock_t issue
  Src/Base/AMReX_OpenMP.H
  Src/Base/AMReX_OpenMP.cpp
Labels: workaround

#3925 Tune PermutationForDeposition for MI250X
  Src/Particle/AMReX_ParticleUtil.H
Labels: performance, GPU

#3953 Fix block size in PermutationForDeposition
  Src/Particle/AMReX_ParticleUtil.H
Labels: bug
