Repository AMReX-Codes/amrex, pull requests merged in 2024-08, with the labels that each got.

#4016 Convert Box to BoxND
  Src/Base/AMReX_BaseFwd.H
  Src/Base/AMReX_Box.H
  Src/Base/AMReX_Box.cpp
  Src/Base/AMReX_IntVect.H
  Src/Base/AMReX_Math.H
  Src/Base/AMReX_ParmParse.H
  Tools/Plotfile/fboxinfo.cpp
Labels: enhancement

#4067 CI: Fix Catalyst CMAKE_PREFIX_PATH
  .github/workflows/catalyst.yml
Labels: test, cleaning

#4068 Plotfile Particles: Fix Error Message
  Src/Extern/HDF5/AMReX_ParticleHDF5.H
  Src/Particle/AMReX_WriteBinaryParticleData.H
Labels: cleaning

#4065 Conduit: Fix SoA Particle
  Src/Extern/Conduit/AMReX_Conduit_Blueprint_ParticlesI.H
Labels: bug

#3684 Bins: Index Type `int`
  Src/Particle/AMReX_BinIterator.H
  Src/Particle/AMReX_DenseBins.H
  Src/Particle/AMReX_NeighborList.H
  Src/Particle/AMReX_NeighborParticlesI.H
  Src/Particle/AMReX_SparseBins.H
Labels: performance, warning

#4071 HDF5: Update BLProfile Name
  Src/Extern/HDF5/AMReX_ParticleHDF5.H
Labels: cleaning

#4056 GPU Device Variable on Intel GPUs
  .github/workflows/intel.yml
  Src/Base/AMReX_GpuDevice.H
  Src/Base/AMReX_GpuLaunch.nolint.H
  Src/Base/AMReX_GpuQualifiers.H
  Tests/CMakeLists.txt
  Tests/DeviceGlobal/CMakeLists.txt
  Tests/DeviceGlobal/GNUmakefile
  Tests/DeviceGlobal/Make.package
  Tests/DeviceGlobal/global_vars.H
  Tests/DeviceGlobal/global_vars.cpp
  Tests/DeviceGlobal/init.cpp
  Tests/DeviceGlobal/main.cpp
  Tests/DeviceGlobal/work.cpp
  Tools/GNUMake/comps/dpcpp.mak
Labels: GPU

#4083 MLEBNodeFDLaplacian: Make it work with AMREX_USE_EB but with no EB
  Src/LinearSolvers/MLMG/AMReX_MLEBNodeFDLaplacian.cpp
Labels: enhancement

#4085 MLEBNodeFDLaplacian: Regression
  Src/LinearSolvers/MLMG/AMReX_MLEBNodeFDLaplacian.cpp
Labels: bug

#4093 Fix a bug in ParmParse::remove
  Src/Base/AMReX_ParmParse.cpp
Labels: bug

#4110 CI: WarpX on `development`
  .github/workflows/apps.yml
Labels: test

#4121 Simplify cache cleanup actions
  .github/workflows/apps.yml
  .github/workflows/bittree.yml
  .github/workflows/clang.yml
  .github/workflows/cleanup-cache-postpr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/codeql.yml
  .github/workflows/cuda.yml
  .github/workflows/gcc.yml
  .github/workflows/hip.yml
  .github/workflows/hypre.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/petsc.yml
  .github/workflows/post-pr.yml
  .github/workflows/smoke.yml
  .github/workflows/sundials.yml
  .github/workflows/windows.yml
Labels: test
