Repository AMReX-Codes/amrex, pull requests merged in 2024-04, with the labels that each got.

#3866 Add `PODVector::assign(value)`
  Src/Base/AMReX_PODVector.H
Labels: enhancement

#3883 `OverrideSync`: Remove Extra Doxygen Parameter
  Src/Base/AMReX_FabArray.H
Labels: bug, documentation

#3871 Add MultiFab::sum(region) and sum_unique(region)
  Src/Base/AMReX_MultiFab.H
  Src/Base/AMReX_MultiFab.cpp
Labels: enhancement

#3893 FabArray: Update Asserts
  Src/Base/AMReX_FabArray.H
Labels: cleaning

#3890 Fix ReorderParticles for PureSoA
  Src/Particle/AMReX_ParticleContainerI.H
Labels: bug

#3894 Fix Assertion
  Src/Base/AMReX_FabArray.H
Labels: bug

#3881 Set AMD wavefront size according to AMReX_AMD_ARCH
  .github/workflows/hip.yml
  Src/Base/AMReX_GpuDevice.H
  Src/Base/AMReX_GpuDevice.cpp
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config_ND.H.in
  Tools/GNUMake/Make.defs
Labels: performance, GPU
