Repository AMReX-Codes/amrex, pull requests merged in 2024-01, with the labels that each got.

#3691 Align GpuComplex to its size
  Src/Base/AMReX_GpuComplex.H
Labels: performance, GPU

#3688 Add special named flag for invalid particles
  Src/Particle/AMReX_Particle.H
Labels: enhancement

#3717 relax constraint that real_comp_names.size() == pc.NumRealComps() + NStructReal for pure SoA plotfiles
  Src/Particle/AMReX_ParticleIO.H
  Src/Particle/AMReX_WriteBinaryParticleData.H
  Tests/Particles/CheckpointRestartSOA/main.cpp
Labels: bug

#3718 Add TypeMultiplier, MakeZeroTuple and IdentityTuple
  Src/Base/AMReX_Reduce.H
  Src/Base/AMReX_Tuple.H
  Src/Base/AMReX_TypeList.H
Labels: enhancement

#3729 Particle Copy Plan: Default Vals
  Src/Particle/AMReX_ParticleCommunication.H
Labels: bug

#3734 Do not use std::forward twice on the same object in AmrParticleLocator
  Src/Particle/AMReX_ParticleLocator.H
Labels: bug

#3732 ParticleCopyPlan for SoA Particles
  Src/Particle/AMReX_ParticleCommunication.H
  Src/Particle/AMReX_ParticleTransformation.H
Labels: bug, GPU

#3733 Add helper function for setting id and cpu simultaneously.
  Src/Particle/AMReX_Particle.H
  Src/Particle/AMReX_ParticleIO.H
Labels: enhancement

#3736 Disable m_aos for SoA Particle
  Src/Particle/AMReX_ParticleMesh.H
  Src/Particle/AMReX_ParticleReduce.H
  Src/Particle/AMReX_ParticleTile.H
Labels: enhancement

#3738 Update AoS Restrict
  Src/Particle/AMReX_ParticleTile.H
Labels: bug
