Repository AMReX-Codes/amrex, pull requests merged in 2025-01, with the labels that each got.

#4277 Fix bug in EBData::randomPointOnEB
  Src/EB/AMReX_EBData.H
Labels: bug

#4285 ParmParse `queryAddWithParser` No Const
  Src/Base/AMReX_ParmParse.H
Labels: bug

#4283 SmallMatrix: Assert Lower Bound Index
  Src/Base/AMReX_SmallMatrix.H
Labels: enhancement

#4286 Make using The_Comms_Arena() for particle communication opt-in
  Src/Particle/AMReX_NeighborParticlesGPUImpl.H
  Src/Particle/AMReX_ParticleContainerBase.H
  Src/Particle/AMReX_ParticleContainerBase.cpp
  Src/Particle/AMReX_ParticleContainerI.H
Labels: performance, GPU

#4290 Fix a memory leak in Open BC solver
  Src/FFT/AMReX_FFT_R2C.H
Labels: bug

#4291 Make ParmParse Parser more robust
  Src/Base/AMReX_ParmParse.cpp
Labels: enhancement

#4293 Fix `AMReX::FFTW` Once
  Tools/CMake/FindAMReXFFTW.cmake
Labels: bug, install

#4298 Fix: PC Tile Copy w/ Names
  Src/Particle/AMReX_ParticleContainer.H
Labels: bug

#4303 CI: Remove ICC/ICPC (Compiler Classic)
  .github/workflows/intel.yml
Labels: test, cleaning

#4295 Fix new coverity scan warnings
  Src/Amr/AMReX_Amr.cpp
  Src/Amr/AMReX_StateData.cpp
  Src/AmrCore/AMReX_AmrCore.cpp
  Src/AmrCore/AMReX_Cluster.H
  Src/Base/AMReX_DistributionMapping.H
  Src/Base/AMReX_DistributionMapping.cpp
  Src/Base/AMReX_OpenMP.cpp
  Src/Base/AMReX_ParmParse.cpp
  Src/Base/AMReX_TinyProfiler.cpp
  Src/Base/AMReX_VisMF.cpp
  Src/LinearSolvers/MLMG/AMReX_MLCellLinOp.H
Labels: warning

#4299 PC: Ensure Uniqueness of SoA Names
  Src/Particle/AMReX_ParticleContainer.H
  Src/Particle/AMReX_ParticleContainerI.H
Labels: bug

#4300 PC: SoA Name Helpers
  Src/Particle/AMReX_ParticleContainer.H
  Src/Particle/AMReX_ParticleContainerI.H
Labels: enhancement

#4272 Fix CMake Compiler Flag Summary: ID Regex Matching
  Tools/CMake/AMReXGenexHelpers.cmake
Labels: bug, install

#4308 Fix includes
  Src/Extern/HDF5/AMReX_ParticleHDF5.H
  Src/Extern/HDF5/AMReX_ParticleUtilHDF5.H
  Src/Extern/HDF5/AMReX_WriteBinaryParticleDataHDF5.H
  Src/Particle/AMReX_MakeParticle.H
  Src/Particle/AMReX_NeighborParticles.H
  Src/Particle/AMReX_NeighborParticlesCPUImpl.H
  Src/Particle/AMReX_NeighborParticlesGPUImpl.H
  Src/Particle/AMReX_NeighborParticlesI.H
  Src/Particle/AMReX_ParticleBufferMap.cpp
  Src/Particle/AMReX_ParticleCommunication.cpp
  Src/Particle/AMReX_ParticleContainer.H
  Src/Particle/AMReX_ParticleContainerBase.cpp
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleIO.H
  Src/Particle/AMReX_ParticleInit.H
  Src/Particle/AMReX_ParticleUtil.cpp
  Src/Particle/AMReX_WriteBinaryParticleData.H
Labels: warning, cleaning

#4309 CUDA On Windows (MSVC)
  .github/workflows/windows.yml
  Src/Base/AMReX_BoxList.cpp
  Src/Base/AMReX_FabArray.H
  Src/Base/AMReX_FabArrayBase.cpp
  Src/Base/AMReX_GpuLaunch.nolint.H
  Src/Base/AMReX_GpuLaunchMacrosC.nolint.H
  Src/Base/AMReX_GpuLaunchMacrosG.nolint.H
  Src/Base/AMReX_GpuUtility.H
  Src/Base/AMReX_MultiFab.cpp
  Src/Base/AMReX_NonLocalBC.H
  Src/Base/AMReX_PODVector.H
  Src/EB/AMReX_EB2_2D_C.cpp
  Src/EB/AMReX_EB2_3D_C.cpp
  Src/EB/AMReX_EBFluxRegister_3D_C.H
  Src/EB/AMReX_EB_STL_utils.cpp
  Src/EB/AMReX_EB_Slopes_2D_K.H
  Src/EB/AMReX_EB_Slopes_3D_K.H
  Src/EB/AMReX_EB_StateRedistSlopeLimiter_K.H
  Src/FFT/AMReX_FFT_Poisson.H
  Src/FFT/AMReX_FFT_R2C.H
  Src/FFT/AMReX_FFT_R2X.H
  Src/LinearSolvers/AMReX_GMRES.H
  Src/LinearSolvers/MLMG/AMReX_MLABecLaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLALaplacian.H
  Src/LinearSolvers/MLMG/AMReX_MLCellLinOp.H
  Src/LinearSolvers/MLMG/AMReX_MLPoisson.H
  Src/Particle/AMReX_ParticleContainerI.H
  Src/Particle/AMReX_ParticleUtil.H
  Tests/DeviceGlobal/CMakeLists.txt
  Tests/EB_CNS/Source/hydro/CNS_hydro_K.H
  Tests/GPU/CNS/Source/hydro/CNS_hydro_K.H
  Tests/LinearSolvers/ABecLap_SP/CMakeLists.txt
  Tools/CMake/AMReXOptions.cmake
Labels: GPU
