Repository AMReX-Codes/amrex, pull requests merged in 2025-07, with the labels that each got.

#4545 CMake: `AMReX_FASTMATH`
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Tools/CMake/AMReXCUDAOptions.cmake
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReX_Config.cmake
  Tools/CMake/AMReX_Config_ND.H.in
Labels: performance, GPU, install

#4520 AMReX SIMD Helpers
  Docs/sphinx_documentation/source/BuildingAMReX.rst
  Src/Base/AMReX_GpuComplex.H
  Src/Base/AMReX_GpuLaunch.H
  Src/Base/AMReX_GpuLaunchFunctsC.H
  Src/Base/AMReX_Math.H
  Src/Base/AMReX_SIMD.H
  Src/Base/AMReX_SmallMatrix.H
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
  Src/Particle/AMReX_Particle.H
  Src/Particle/AMReX_ParticleTile.H
  Tools/CMake/AMReXConfig.cmake.in
  Tools/CMake/AMReXOptions.cmake
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/CMake/AMReXSetDefines.cmake
  Tools/CMake/AMReX_Config_ND.H.in
Labels: enhancement, performance

#4575 Update Math::sincos and sincospi
  Src/Base/AMReX_Math.H
Labels: bug

#4585 Ascent: 0.9.3
  .github/workflows/ascent.yml
Labels: test
