Repository AMReX-Codes/amrex, pull requests merged in 2025-06, with the labels that each got.

#4517 Add `AMReX_Order.H`
  Src/Base/AMReX_Array.H
  Src/Base/AMReX_Order.H
  Src/Base/AMReX_SmallMatrix.H
  Src/Base/CMakeLists.txt
  Src/Base/Make.package
Labels: cleaning

#4515 Fix GPU communication for non-arithmetic types
  Src/Base/AMReX_FBI.H
  Src/Base/AMReX_FabArrayUtility.H
  Src/Base/AMReX_MultiFab.cpp
  Src/Base/AMReX_PCI.H
  Tests/CMakeLists.txt
  Tests/CommType/CMakeLists.txt
  Tests/CommType/GNUmakefile
  Tests/CommType/Make.package
  Tests/CommType/main.cpp
Labels: bug

#4523 Modernize roctx Annotations
  Src/Base/AMReX_GpuDevice.cpp
  Src/Base/AMReX_TinyProfiler.cpp
  Tools/CMake/AMReXParallelBackends.cmake
  Tools/GNUMake/comps/hip.mak
Labels: GPU

#4521 Spack Smoke Test: Fix HIP and Add SYCL
  Tests/SpackSmokeTest/CMakeLists.txt
Labels: GPU, install
